{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "project.serviceAccountName" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
{{- end -}}
